# Day 3 - NumPy Fundamentals

**Name:** Manish Saini  
**Internship:** AI & ML Internship  
**Organization:** Codomax Digital Solutions  

## Objective

The objective of this task is to learn the fundamentals of NumPy, including array creation, indexing, slicing, and mathematical operations. NumPy provides powerful tools for numerical computing and is widely used in data science and machine learning.

In [ ]:
import numpy as np

# Create Arrays
arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(arr.dtype)
print(arr.shape)

# Indexing
print(arr[0])
print(arr[-1])

# Slicing
print(arr[1:4])

# Mathematical Operations
print(arr + 5)
print(arr * 2)

# Statistics

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))

[10 20 30 40 50]
int64
(5,)
10
50
[20 30 40]
[15 25 35 45 55]
[ 20  40  60  80 100]
Sum: 150
Mean: 30.0
Max: 50
Min: 10


# Conclusion

Successfully learned the basics of NumPy, including array creation, indexing, slicing, mathematical operations, and statistical functions. These concepts form the foundation for data analysis and machine learning tasks.